export const m99 = `CREATE TABLE IF NOT EXISTS m99(
    KALG INTEGER,
    KAIG SMALLINT,
    GOLN SMALLINT,
    GOLP SMALLINT,
    GOPL NUMERIC(9.1),
    OBLA SMALLINT
    );`;

export const M00  = `CREATE TABLE IF NOT EXISTS M00(
    CODEGIS text,
    KALG INTEGER,
    KAIG SMALLINT,
    KAWN SMALLINT,
    KAVN SMALLINT,
    KARN SMALLINT
    KAWN SMALLINT,
    KAKL INTEGER,
    KARA SMALLINT,
    KAGE SMALLINT,
    MAPL NUMERIC(9.1),
    MAIS SMALLINT,
    MARI NUMERIC(9.1),
    MAIR SMALLINT,
    MATN SMALLINT,
    MAEK SMALLINT,
    PPOV SMALLINT,
    PPPZ SMALLINT,
    PPGL SMALLINT,
    MARR INTEGER,
    OBLA INTEGER
    );`;

export const M01  = `CREATE TABLE IF NOT EXISTS M01(
    KAVN SMALLINT,
    KARN SMALLINT,
    KAVS NUMERIC(9.1),
    KAKZ SMALLINT,
    KAKI SMALLINT,
    KAZU SMALLINT,
    KAVQ SMALLINT,
    PPGH SMALLINT
    );`;

export const M02  = `CREATE TABLE IF NOT EXISTS M02(
    KARD NUMERIC(9.1),
    KAVR SMALLINT
    );`;

export const M03  = `CREATE TABLE IF NOT EXISTS M03(
    KARX SMALLINT,
    KARH SMALLINT,
    KAHM SMALLINT
    );`;

export const M04  = `CREATE TABLE IF NOT EXISTS M04(
    KBEV SMALLINT,
    KBET SMALLINT,
    KBES SMALLINT
   );`;

export const M05  = `CREATE TABLE IF NOT EXISTS M05(
    KAPL INTEGER,
    KAB_ SMALLINT,
    KATL SMALLINT,
    KATU SMALLINT,
    KACO SMALLINT,
    KA3P INTEGER,
    KAVE SMALLINT,
    KAHS SMALLINT,
    KAGV SMALLINT,
    KAUV SMALLINT,
    KAPP NUMERIC(3.2),
    KAMP NUMERIC(9.2),
    KAMZ NUMERIC(9.2)
    );`;

export const M07  = `CREATE TABLE IF NOT EXISTS M07(
    KBJV SMALLINT,
    KBKP SMALLINT,
    KBKS SMALLINT,
    KBTV SMALLINT
    );`;

export const M08  = `CREATE TABLE IF NOT EXISTS M08(
    KAZO SMALLINT,
    KAZQ SMALLINT
    );`;

export const M09  = `CREATE TABLE IF NOT EXISTS M09(
    KA1P SMALLINT,
    KA1N SMALLINT,
    KAT1 SMALLINT
    );`;

export const M10  = `CREATE TABLE IF NOT EXISTS M10(
    KAJA SMALLINT,
    KASS SMALLINT,
    KASP INTEGER,
    KAA_ SMALLINT,
    KAH_ NUMERIC(3.1),
    KAD_ NUMERIC(3.1) ,
    KAND SMALLINT,
    KANT NUMERIC(5.1),
    KAP_ NUMERIC(3.2),
    KAPR SMALLINT,
    KAMG SMALLINT,
    KAPH SMALLINT,
    KAMJ NUMERIC(9.2)
    );`;

export const M11  = `CREATE TABLE IF NOT EXISTS M11(
    KNSV SMALLINT,
    KNSW SMALLINT,
    KNSK SMALLINT,
    KNMK SMALLINT,
    KNRM SMALLINT,
    KNMR SMALLINT,
    KNSR NUMERIC(3.1) ,
    KNVR NUMERIC(3.1),
    KNKM NUMERIC(3.1) 
    );`;

export const M12  = `CREATE TABLE IF NOT EXISTS M12(
    KOPV SMALLINT,
    KO1V SMALLINT,
    KO2V SMALLINT,
    KOPJ SMALLINT,
    KON1 SMALLINT,
    KOP1 SMALLINT
    );`;

export const M13  = `CREATE TABLE IF NOT EXISTS M13(
    KPHT NUMERIC(9.1),
    KPSO SMALLINT,
    KPPT NUMERIC(9.1),
    KPKD SMALLINT,
    KPND SMALLINT,
    KPVI NUMERIC(9.1),
    KPPO SMALLINT
    );`;

export const M14  = `CREATE TABLE IF NOT EXISTS M14(
    KQKU SMALLINT,
    KQ1W SMALLINT,
    KQN1 SMALLINT,
    KQOS SMALLINT
    );`;

export const M15  = `CREATE TABLE IF NOT EXISTS M15(
    KRMV SMALLINT,
    KRPJ SMALLINT,
    KRPP INTEGER,
    KROB SMALLINT,
    KROZ SMALLINT,
    KRNS SMALLINT,
    KRVS NUMERIC(9.1),
    KRLZ SMALLINT,
    KRDZ SMALLINT,
    KRST SMALLINT,
    KRVN SMALLINT,
    KRRN SMALLINT
    );`;

export const M16  = `CREATE TABLE IF NOT EXISTS M16(
    KSSG SMALLINT,
    KSSP INTEGER,
    KSA_ SMALLINT,
    KSH_ NUMERIC(3.1),
    KSEI SMALLINT,
    KSUQ NUMERIC(5.1),
    KSUB SMALLINT
    );`;

export const M17  = `CREATE TABLE IF NOT EXISTS M17(
    KTPN SMALLINT,
    KTTP SMALLINT,
    KTUQ NUMERIC(5.1),
    KTUK SMALLINT,
    KTSP INTEGER,
    KTNZ SMALLINT,
    KTSU SMALLINT,
    KTCZ SMALLINT
    );`;

export const М18  = `CREATE TABLE IF NOT EXISTS М18(
    KJSD INTEGER,
    KJST SMALLINT,
    KJPS SMALLINT,
    KJOP SMALLINT,
    KJWP NUMERIC(9.1),
    KJNS SMALLINT,
    KJVX SMALLINT
    );`;

export const М19  = `CREATE TABLE IF NOT EXISTS М19(
    KUBT SMALLINT,
    KUBR SMALLINT,
    KUTS NUMERIC(9.1),
    KUSP INTEGER,
    KUNZ SMALLINT
    );`;

export const М20  = `CREATE TABLE IF NOT EXISTS М20(
    KVPK SMALLINT,
    KVMP SMALLINT,
    KVSP INTEGER,
    KVM_ SMALLINT,
    KVML SMALLINT,
    KVMD SMALLINT
    );`;

export const М21  = `CREATE TABLE IF NOT EXISTS М21(
    KWLT SMALLINT,
    KWLE SMALLINT,
    KWL1 SMALLINT,
    KWOD SMALLINT,
    KWLS SMALLINT,
    KWLU SMALLINT,
    KWRD SMALLINT,
    KWL2 SMALLINT
    );`;

export const М22  = `CREATE TABLE IF NOT EXISTS М22(
    KXCP SMALLINT,
    KXCB SMALLINT,
    KXSR NUMERIC(3.1),
    KXVR NUMERIC(3.1),
    KXCJ SMALLINT,
    KXKM SMALLINT,
    KXCK SMALLINT,
    KXUQ NUMERIC(5.1) ,
    KXPN SMALLINT
    );`;

export const М23  = `CREATE TABLE IF NOT EXISTS М23(
    KY00 SMALLINT
    );`;

export const М24  = `CREATE TABLE IF NOT EXISTS М24(
    KZOJ SMALLINT,
    KZOK SMALLINT,
    KZPP INTEGER,
    KZRO NUMERIC(3.1),
    KZRV NUMERIC(3.1),
    KZBZ SMALLINT
    );`;

export const М25  = `CREATE TABLE IF NOT EXISTS М25(
    K3NE SMALLINT,
    K3SP INTEGER,
    K3A_ SMALLINT,
    K3CI SMALLINT,
    K3CR NUMERIC(3.1),
    K3VR NUMERIC(3.1),
    K3KM INTEGER
    );`;

export const М26  = `CREATE TABLE IF NOT EXISTS М26(
    QLNN SMALLINT,
    QLGR SMALLINT,
    QLNT SMALLINT,
    QLWN NUMERIC(9.1)   ,
    QLIG NUMERIC(9.1),
    QLNI SMALLINT,
    QLXN SMALLINT
    );`;

export const М27  = `CREATE TABLE IF NOT EXISTS М27(
    QMVN SMALLINT,
    QMVS NUMERIC(9.1),
    QMKZ SMALLINT,
    QMSS SMALLINT,
    QMSP INTEGER,
    QMGV SMALLINT,
    QMP_ NUMERIC(3.2),
    QM1P SMALLINT
    );`;

export const М28  = `CREATE TABLE IF NOT EXISTS М28(
    PSTI SMALLINT,
    PSNO SMALLINT,
    PSDO SMALLINT,
    PSSI SMALLINT,
    PSKR SMALLINT,
    PSKO SMALLINT,
    PSOC SMALLINT,
    PSLO SMALLINT
    );`;

export const  М29 = `CREATE TABLE IF NOT EXISTS М29(
    PRTI SMALLINT,
    PRNO SMALLINT,
    PRDO SMALLINT,
    PRSI SMALLINT,
    PRKR SMALLINT,
    PRKO SMALLINT
    );`;

export const М30  = `CREATE TABLE IF NOT EXISTS М30(
    QPEM SMALLINT,
    QPPM SMALLINT,
    QP2M SMALLINT,
    QP3M SMALLINT,
    QPMV SMALLINT,
    QPVP SMALLINT,
    QPVV NUMERIC(3.1),
    QPSV SMALLINT,
    QPPG SMALLINT,
    QPGM SMALLINT,
    QPGZ SMALLINT
    );`;

export const М31  = `CREATE TABLE IF NOT EXISTS М31(
    RZY1 NUMERIC(9.2),
    RZY5 NUMERIC(9.2),
    RZC7 NUMERIC(9.2),
    RZK4 NUMERIC(9.2),
    RZS9 NUMERIC(9.2),
    RZPD NUMERIC(9.2),
    RZPT NUMERIC(9.2),
    RZPG NUMERIC(9.2)
    );`;

export const М88  = `CREATE TABLE IF NOT EXISTS М88(
    SPGK SMALLINT,
    ZVGK NUMERIC(3.2),
    ZVLD NUMERIC(3.2),
    ZVDL NUMERIC(3.2),
    SPRD SMALLINT,
    ZVRD SMALLINT,
    KNPT SMALLINT,
    SPTT SMALLINT,
    GNTT SMALLINT,
    GNVP SMALLINT,
    OZKP SMALLINT,
    GOSP SMALLINT,
    KRUT SMALLINT,
    KLVK SMALLINT,
    CHNS SMALLINT,
    STOV SMALLINT,
    SFLV SMALLINT,
    ZONA SMALLINT,
    TYPE SMALLINT,
    PODT SMALLINT,
    VID SMALLINT
    );`;

export const saw = `CREATE TABLE IF NOT EXISTS saw(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    KALG INTEGER,
    KAIG SMALLINT,
    KAWN SMALLINT,
    KAVN SMALLINT,
    KARN SMALLINT
    );`;

export const meta_by_maquette = `CREATE TABLE IF NOT EXISTS meta_by_maquette(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name text,
    number_of_maquette text,
    field_name text,
    mnemo_code text,
    data_type text
    );`;

